
def build(bld):

    bld(features = 'cxx cxxprogram',
        target = 'simple_example',
        source = 'simple_example.cpp',
        lib = ['crypto'],        
        use = ['harpocrates_includes', 'harpocrates'])    